# Generated by Django 6.0.7 on 2026-07-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': '留言表单', 'verbose_name_plural': '留言管理'},
        ),
    ]
