# Generated by Django 6.0.7 on 2026-09-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contract_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='英文名称')),
                ('category', models.CharField(choices=[('冷暖净风器', '冷暖净风器'), ('电风扇', '电风扇'), ('暖风机', '暖风机'), ('小太阳', '小太阳')], default='电风扇', max_length=50, verbose_name='产品类型')),
                ('desc', models.TextField(blank=True, verbose_name='产品描述')),
                ('desc_en', models.TextField(blank=True, verbose_name='英文描述')),
                ('specs', models.TextField(blank=True, verbose_name='中文规格（每行一条）')),
                ('specs_en', models.TextField(blank=True, verbose_name='英文规格（每行一条）')),
                ('image', models.FileField(blank=True, upload_to='products/', verbose_name='产品图片')),
                ('legacy_image', models.CharField(blank=True, help_text='当未上传新图片时使用，例如 /products/LN01.jpg', max_length=300, verbose_name='图片路径')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('active', models.BooleanField(default=True, verbose_name='上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品管理',
                'db_table': 'product',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
